fix ts error
mark43/id-parser-43 pull request #13
Opened 2021-04-17 03:51 UTC by NavinSeth

2021-04-17 03:59 UTC, robotmlg commented on src/types.ts
> +    lastName: TruncationT;
sorry, `familyName` covers this, my test should use `familyName`

2021-04-17 04:03 UTC, NavinSeth commented on test/parse.test.ts
>    it('has last name truncation mark', () => {
Removing this test then since you already have one for first name truncation mark.

2021-04-18 14:06 UTC, robotmlg requested changes

2021-04-18 14:06 UTC, robotmlg commented on test/parse.test.ts
> +    expect(parse(aamvaSample).identification.truncation.middleName).toEqual(
```suggestion
    expect(parse(aamvaSample).identification.truncation.familyName).toEqual(
```

2021-04-18 14:06 UTC, robotmlg approved these changes

2021-04-18 15:31 UTC, merged